### ISSUE TITLE
Adding chapters 1-80

### ISSUE THREAD

**Issue by infernalsaber** [princedizzytoon/kaoruhana#1]
Hi, I'm unsure what other channels I can contact you on, so I'm raising this here
But would it be possible for you to integrate chapters before ch80 (from eg. mangasee) into your gist?
Your gist is widely passed around in the kaoruhana community, so that would help the newcomers have a single source.

Would be glad to help

**Comment by princedizzytoon** [comment]
I assumed people were using MD to read those chapters, but I can try

**Comment by princedizzytoon** [comment]
Done.
